### ISSUE TITLE
Code of Conduct

### ISSUE THREAD

**Issue by gcharest** [gcdevops/strategie-devops-strategy#1]
Need to work on a Code of Conduct: https://www.contributor-covenant.org/ is a good example.

We had it modified the AIA project:

https://github.com/canada-ca/aia-eia-js/blob/master/CODE_OF_CONDUCT.md

**Comment by s-laugh** [comment]
Is there any reason we can't copy it from the AIA project? I can't think of any.  
Would just need to update the attribution.

**Comment by gcharest** [comment]
No reason, we can just update attribution. We did modify a bit to match our project at the time though.

**Comment by gcharest** [comment]
Thanks for the PR!
